### ISSUE TITLE
не находит класс

### ISSUE THREAD

**Issue by Igor-Men** [ZloeSabo/speechkit-php#1]
igor@igor-H81M-S2V:/var/www/shop2.localhost$ php -f index1.php 
PHP Fatal error:  Class 'SpeechKit\SpeechContent\RawDataSpeech' not found in /var/www/shop2.localhost/lib/SpeechKit/SpeechContent/SpeechFactory.php on line 16

public static function fromData($data)
    {
        if(is_file($data)) {
            return new File($data);
        } else {
            return new RawDataSpeech($data); // проблема в то м что не находит класса
        }
    }
// закомитил на git hub то что у меня получилось https://github.com/Igor-Men/test-yandex-kit

**Comment by ZloeSabo** [comment]
RawData не был реализован. Фикс залил, теперь всё должно быть в порядке.

**Comment by Igor-Men** [comment]
хорошо, спасибо) а то я первый раз юзаю composer думаю может че-то не доделал.

**Comment by Igor-Men** [comment]
Евгений настроил все работает!!  Спасибище, удачного вам дня))
